# fly.toml app configuration file copied from another project
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'html-wiki'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 100

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
